### ISSUE TITLE
Error: Cannot find module 'eslint-config-xo' @ npm2

### ISSUE THREAD

**Issue by htanjo** [sindresorhus/eslint-config-xo-space#3]
Since v0.10.0, ESLint shows the following error if I install `eslint-config-xo-space` using npm v2.
Probably 3993855a35bb3a29ae0bacd043d069a2539525ed causes this issue.

```
/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:361
            throw e;
            ^

Error: Cannot find module 'eslint-config-xo' from '/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules'
Referenced from: xo-space
Referenced from: /Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/package.json
    at Function.module.exports [as sync] (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:417:38)
    at load (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:436:24)
    at /Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:338:28)
    at load (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:464:22)
    at /Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/hiroyuki.tanjo/lab/_temp/eslint-config-debug/node_modules/eslint/lib/config/config-file.js:338:28)
npm ERR! Test failed.  See above for more details.
```

This is my simplified package.json.
It works on `node v5.7.0 (npm v3.6.0)`, but shows the error when I use `node v4.3.1 (npm v2.14.12)`.

```json
{
  "scripts": {
    "test": "eslint index.js"
  },
  "devDependencies": {
    "eslint": "^2.2.0",
    "eslint-config-xo-space": "^0.10.0"
  },
  "eslintConfig": {
    "extends": "xo-space"
  }
}
```

**Comment by sindresorhus** [comment]
Can you try with ESLint 2.3.0? There was a bug with the shareable configs that was fixed in that release.

**Comment by htanjo** [comment]
Thanks so much! It works on ESLint 2.3.0 without error.
